### PR TITLE
Problem: ClusterIP resource may sporadically fail and migrate to another node (#196)

### PR DESCRIPTION
**Pull request by azheregelya**
Cherry-pick to cortx-1.0 from pull request #196.

### CODE REVIEW

**Comment by azheregelya** [comment]
@andriytk @mssawant @ajaysrivas could you please review/approve?

**Comment by andriytk** [comment]
LGTM

**Review by andriytk — APPROVED** [review]

**Review by chumakd — APPROVED** [review]

**Comment by andriytk** [comment]
Is there any change to figure out why the ClusterIP failed?

**Comment by azheregelya** [comment]
@andriytk may be it will be possible to do this on alive system. So far, resource agent doesn't log why it fails.

**Review by ajaysrivas — APPROVED** [review]

**Pull request merged**
