### PR TITLE
EOS-19431: Unstandby the node even when it is in standby mode with running resource

### PR DESCRIPTION
**Pull request by VijayThakkar132**
Signed-off-by: Vijaykumar Thakkar <vijaykumar.thakkar@seagate.com>

## Problem Statement
<pre>
  <code>
  Story Ref (if any):
    EOS-19431
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  Yes
  </code>
</pre>
## Problem Description
<pre>
  <code>
    QA has observed that node start operation ignored when node is in standby mode with running resource.
  </code>
</pre>
## Solution
<pre>
  <code>
    As discussed in the team's chat, I have removed "standby node with running resources" condition and combined with "standby" condition.
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
    Validation done on 3 node cluster and it works fine
  </code>
</pre>

### CODE REVIEW

**Review by indrajitzagade — APPROVED** [review]
@VijayThakkar132 Please update here with the UT results.

**Comment by VijayThakkar132** [comment]
> @VijayThakkar132 Please update here with the UT results.

I have shared rpms with Jyoti and waiting for the results.

**Review by ajay-paratmandali — APPROVED** [review]

**Comment by VijayThakkar132** [comment]
> > @VijayThakkar132 Please update here with the UT results.
> 
> I have shared rpms with Jyoti and waiting for the results.

@indrajitzagade  Validation done and able to start node when it was in standby mode with active resources

**Comment by indrajitzagade** [comment]
> 
> 
> > > @VijayThakkar132 Please update here with the UT results.
> > 
> > 
> > I have shared rpms with Jyoti and waiting for the results.
> 
> @indrajitzagade Validation done and able to start node when it was in standby mode with active resources

Sure, thanks for the update.

**Review by azheregelya — APPROVED** [review]

**Pull request merged**
