### PR TITLE
Add a Codacy badge to README.md

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
Adding a new Codacy badge to repository README. The current badge is not working as required (Should point to cortx-ha dashboard but points to the Seagate dashboard).

**Comment by indrajitzagade** [comment]
@gauravchaudhari02 Please fill-up the PR tempate

**Comment by indrajitzagade** [comment]
Looks like this PR was autogenerated on some codacy change.

**Review by indrajitzagade — APPROVED** [review]

**Review by ajaysrivas — APPROVED** [review]

**Comment by gauravchaudhari02** [comment]
Closing this PR as it is automatically generated by Codacy and not able to solve merge conflicts as the source branch is not reachable.

**Comment by gauravchaudhari02** [comment]
Created new PR - https://github.com/Seagate/cortx-ha/pull/171

**Pull request closed without merging**
