### PR TITLE
Eos 15127 SW update failed at components.ha.iostack-ha.post_update

### PR DESCRIPTION
**Pull request by ArchanaLimaye**
## Problem Statement
<pre>
  <code>
  Story Ref (if any):
   Error was reported in update from build 454->463 using csm cli
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  Yes/No
  </code>
</pre>
## Problem Description
<pre>
  <code>
    SW update failed at components.ha.iostack-ha.post_update  from build 454->463 using csm cli
  </code>
</pre>
## Solution
<pre>
  <code>
    syntax error found in sspl resource promote and demote is fixed
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
  -
  </code>
</pre>

### CODE REVIEW

**Comment by andriytk** [comment]
Which exactly error?

**Review by ujjwalpl — APPROVED** [review]

**Comment by ArchanaLimaye** [comment]
> Which exactly error?

This is for https://github.com/Seagate/cortx-ha/commit/d33662a7dd5d901687223b6dee30591c056195b9#diff-f7fe5afdcccc4d5c4aa09b1d2b083968ac5e4bdd683e6a1ad8c11a668b410415

**Comment by andriytk** [comment]
It does not answer my question, sorry.

**Comment by andriytk** [comment]
Ok, I see the error from the Jira ticket:

```
Nov 17 07:02:36 smc65-m01.colo.seagate.com lrmd[75581]: notice: sspl_promote_0:31522:stderr [ /usr/lib/ocf/resource.d/cortx/sspl: line 159: [: too many arguments ]
```

**Review by andriytk — APPROVED** [review]

**Review by saurabhkhanvilkar — APPROVED** [review]

**Review by mssawant — APPROVED** [review]

**Pull request merged**
