### PR TITLE
Merge cortx-ha main into stable

### PR DESCRIPTION
**Pull request by indrajitzagade**
Merge cortx-ha main into stable

### CODE REVIEW

**Comment by indrajitzagade** [comment]
run vm-deployment

**Comment by indrajitzagade** [comment]
run vm-deployment

**Comment by indrajitzagade** [comment]
run vm-deployment

**Comment by indrajitzagade** [comment]
ok to test

**Comment by indrajitzagade** [comment]
run vm-deployment

**Comment by indrajitzagade** [comment]
run vm-deployment

**Comment by indrajitzagade** [comment]
run vm-deployment

**Review by ajay-paratmandali — APPROVED** [review]

**Comment by indrajitzagade** [comment]
The deployment was successful here: http://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/Deployment/job/OPTIMIZED_HW_DEPLOYMENT/230/
Merging based on this deployment result.

**Pull request merged**
