### PR TITLE
CORTX-30057 : HA should accept events from CSM for resource status

### PR DESCRIPTION
**Pull request by akash2144**
Signed-off-by: Akash Dudhane <akash.a.dudhane@seagate.com>

# Problem Statement
- Any 'source' based checks in fault_tolerance should be enhanced to accept 'csm' as a source for the events

# Design
-  Currently no checks present in HA for source filed, which are applicable for csm "failed" event.
-  Add "source" & "message_type" constants for CSM.

# Coding
-  [x] Coding conventions are followed and code is consistent

# Testing 
- [x] Unit and System Tests are added :  
[test_results.txt](https://github.com/Seagate/cortx-ha/files/8462020/test_results.txt)
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM

# Review Checklist 
- [x] PR is self reviewed
- [x] JIRA number/GitHub Issue added to PR
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained
- [ ] Is there a change in filename/package/module or signature? [Y/N]: N
- [ ] If yes for above point, is a notification sent to all other cortx components? [Y/N] NA
- [ ] Side effects on other features (deployment/upgrade)? [Y/N] N
- [ ] Dependencies on other component(s)? [Y/N] N
-     If yes for above point, post link to the corresponding PR.

# Review Checklist 
- [ ] Is perfline test run and the report with and without the changes updated in the PR? [Y/N]: 

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by mariyappanp** [comment]
Test result has failed type event only. Did you verify 'online' event getting updated after 'offline' status? @akash2144

**Comment by akash2144** [comment]
> Test result has failed type event only. Did you verify 'online' event getting updated after 'offline' status? @akash2144

From csm we're expecting only permanent node failure i.e. "failed" event so I've added test only for failed events.
For testing "online" event I have used the source as monitor & tested :

[root@cortx-ha-headless-svc health_generator]# python3 mock_health_event_publisher.py publish -f config.json              
Publishing health event {"header": {"version": "1.0", "timestamp": "1649414757.0393233", "event_id": "1649414757.039323379f6f45eb267423caf7bd92fd56352e1"}, "payload": {"source": "monitor", "cluster_id": "118196a1d1094388be697ba3db13e367", "site_id": "NOT_DEFINED", "rack_id": "NOT_DEFINED", "storageset_id": "1", "node_id": "9b235fdd12774ea48c71dd7835461277", "resource_type": "node", "resource_id": "9b235fdd12774ea48c71dd7835461277", "resource_status": "online", "specific_info": {"generation_id": "cortx-server-ssc-vm-g4-rhev4-0763-68c947c544-lslmv", "pod_restart": 0}}}
Sleeping for 2 seconds
[root@cortx-ha-headless-svc health_generator]#

**Health Monitor Logs**
2022-04-08 10:45:58 health_monitor [7]: INFO [publish] Sending action event {"header": {"version": "1.0", "timestamp": "1649414758.1090193", "event_id": "1649414758.10901938145f5f6a5324ebd815e62d567b5160b"}, "payload": {"source": "monitor", "cluster_id": "118196a1d1094388be697ba3db13e367", "site_id": "NOT_DEFINED", "rack_id": "NOT_DEFINED", "storageset_id": "9b235fdd12774ea48c71dd7835461277", "node_id": "9b235fdd12774ea48c71dd7835461277", "resource_type": "node", "resource_id": "9b235fdd12774ea48c71dd7835461277", "resource_status": "online", "specific_info": {"generation_id": "cortx-server-ssc-vm-g4-rhev4-0763-68c947c544-lslmv", "pod_restart": 0}}} to component hare

Consul keys :
cortx>ha>v1>cortx>ha>system>cluster>118196a1d1094388be697ba3db13e367>site>NOT_DEFINED>rack>NOT_DEFINED>node>9b235fdd12774ea48c71dd7835461277>health:{"events": [{"event_timestamp": "1649414757.0393233", "created_timestamp": "1649414758", "status": "starting", "specific_info": {"generation_id": "cortx-server-ssc-vm-g4-rhev4-0763-68c947c544-lslmv", "pod_restart": 0}}, {"event_timestamp": "1649414666.131218", "created_timestamp": "1649414667", "status": "failed", "specific_info": {"generation_id": "cortx-server-ssc-vm-g4-rhev4-0763-68c947c544-lslmv", "pod_restart": 0}}], "action": {"modified_timestamp": "1649414758", "status": "pending"}, "attributes": {}}

Adding same details in test_results.py file

**Review by mukhtar-inamdar — APPROVED** [review]

**Review by mariyappanp — APPROVED** [review]

**Review by gauri-bhosale — APPROVED** [review]

**Review by gargpalak048 — APPROVED** [review]
LGTM

**Review by Madhura-08 — APPROVED** [review]

**Review by shaileshsvc — APPROVED** [review]

**Review by mukhtar-inamdar — APPROVED** [review]

**Comment by ArchanaLimaye** [comment]
In test_results.txt , in Health_monitor logs, the event is seen as published to Hare.

2022-04-08 13:27:39 health_monitor [7]: INFO [publish] Sending action event {"header": {"version": "1.0", "timestamp": "1649424459.8114069", "event_id": "1649424459.8114069ecd40565df9f406e9c986cf437bac84e"}, "payload": {"source": "csm", "cluster_id": "01d9cee8d6b84fa7bca41cb5853802b3", "site_id": "NOT_DEFINED", "rack_id": "NOT_DEFINED", "storageset_id": "e8d24a7ac6554cc8b55abfd58c025233", "node_id": "e8d24a7ac6554cc8b55abfd58c025233", "resource_type": "node", "resource_id": "e8d24a7ac6554cc8b55abfd58c025233", "resource_status": "failed", "specific_info": ""}} to component hare

Here the source is set to CSM

@shaileshsvc will Hare refer to this source anytime ? I do not think so but want to confirm
@akash2144 please check with Hare if they use this source field or its ignored

**Pull request merged**
