### PR TITLE
fault_k8s to main merge

### PR DESCRIPTION
**Pull request by ArchanaLimaye**
# Problem Statement
fault_k8s to main merge

# Design
fault_k8s to main merge

# Coding 
-  [ ] Coding conventions are followed and code is consistent

  NA: Branch to branch merge, no code changes

# Testing 
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
  
NA: Branch to branch merge, no code changes

# Review Checklist  
- [ ] PR is self reviewed
- [ ] JIRA number/GitHub Issue added to PR
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained
- [ ] Is there a change in filename/package/module or signature? [Y/N]: 
- [ ] If yes for above point, is a notification sent to all other cortx components? [Y/N]
- [ ] Side effects on other features (deployment/upgrade)? [Y/N]
- [ ] Dependencies on other component(s)? [Y/N]
-     If yes for above point, post link to the corresponding PR.

  NA: Branch to branch merge, no code changes

# Review Checklist 
- [ ] Is perfline test run and the report with and without the changes updated in the PR? [Y/N]: 

  NA: Branch to branch merge, no code changes

# Documentation  
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

  NA: Branch to branch merge, no code changes

### CODE REVIEW

**Review by Madhura-08 — APPROVED** [review]

**Review by Madhura-08 — COMMENTED** [review]
DCO check is failing again.

**Comment by ArchanaLimaye** [comment]
>DCO check is failing again.

Yes, this was discussed with Mukul and we will be taking an exception for this failure and merge once reviews are done

**Review by mukhtar-inamdar — APPROVED** [review]

**Review by shaileshsvc — APPROVED** [review]
Approved.

**Review by akash2144 — APPROVED** [review]

**Review by indrajitzagade — APPROVED** [review]

**Comment by indrajitzagade** [comment]
Please update the PR template, please check what is applicable.

**Comment by mukul-seagate11** [comment]
DCO check is failing so its considered as an exception to merge

**Comment by ArchanaLimaye** [comment]
> Please update the PR template, please check what is applicable.
Updated

**Pull request merged**
