### PR TITLE
CORTX-30050 cluster status: system health updates

### PR DESCRIPTION
**Pull request by ArchanaLimaye**
# Problem Statement
- Cluster status gets updated in system health 

# Design
- Cluster status gets updated in system health 

# Coding
-  [x] Coding conventions are followed and code is consistent

# Testing 
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
 Testing details are in https://jts.seagate.com/secure/attachment/515400/test_results.txt

# Review Checklist 
- [x] PR is self reviewed
- [ ] JIRA number/GitHub Issue added to PR
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained
- [ ] Is there a change in filename/package/module or signature? [Y/N]: 
- [ ] If yes for above point, is a notification sent to all other cortx components? [Y/N]
- [ ] Side effects on other features (deployment/upgrade)? [Y/N]
- [ ] Dependencies on other component(s)? [Y/N]
-     If yes for above point, post link to the corresponding PR.

# Review Checklist 
- [ ] Is perfline test run and the report with and without the changes updated in the PR? [Y/N]: 

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by mariyappanp** [comment]
Is this to only change specific_info type from null to empty dictionary ? Please confirm.

**Comment by ArchanaLimaye** [comment]
>Is this to only change specific_info type from null to empty dictionary ? Please confirm.
Yes. As mentioned in DSU today, no other change was needed

**Review by mariyappanp — APPROVED** [review]

**Review by Madhura-08 — COMMENTED** [review]
@ArchanaLimaye Sorry, but I am not getting the main purpose of this ticket?
Can you please explain?

**Review by Madhura-08 — APPROVED** [review]

**Review by gargpalak048 — APPROVED** [review]

**Review by akash2144 — APPROVED** [review]

**Review by shaileshsvc — APPROVED** [review]
Approved

**Pull request merged**
