### PR TITLE
CORTX-30030: cluster status: Event analyzer filter and parse logic enhancement

### PR DESCRIPTION
**Pull request by Madhura-08**
…hancement

- HA needs to act on the events received from HARE for cluster state change based
  on the defined algorithm. This state needs to be added in the system health for the
  cluster key. So, once that alert is received by fault_monitor, this needs to be passed
  from event analyzer filter and parser. Filter will pass it based on the alert resource
  type. Currently, filter list has node, disk, cvg as resource type. So, this list needs
  to be modified for "cluster" resource type as well.

Signed-off-by: Madhura Mande <madhura.mande@seagate.com>

# Problem Statement
- https://jts.seagate.com/browse/CORTX-30030
HA should accept cluster state change alert from HARE and HA Event Analyzer should able to filter and parse it to system health for further processing.
 
# Design
HA resource type Event Analyzer filter list needs to be updated for "cluster" resource type so that cluster state alert with resource_type as "cluster" will be filtered. This is possible at the mini provisioning phase

# Coding
-  [ ] Coding conventions are followed and code is consistent

# Testing 
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM

# Review Checklist 
- [x] PR is self reviewed
- [x] JIRA number/GitHub Issue added to PR
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained
- [ ] Is there a change in filename/package/module or signature? [Y/N]: N
- [ ] If yes for above point, is a notification sent to all other cortx components? [Y/N] N
- [ ] Side effects on other features (deployment/upgrade)? [Y/N] N
- [ ] Dependencies on other component(s)? [Y/N] N
-     If yes for above point, post link to the corresponding PR.

# Review Checklist 
- [ ] Is perfline test run and the report with and without the changes updated in the PR? [Y/N]: 

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

Test results:
[CORTX-30030_Test_Results](https://jts.seagate.com/secure/attachment/513127/CORTX-30030_Test_Results.txt)

### CODE REVIEW

**Comment by ArchanaLimaye** [comment]
@Madhura-08  please add testing details in test_results.txt and attach it to the PR

**Comment by shaileshsvc** [comment]
Can you please add testing details.

**Review by gargpalak048 — APPROVED** [review]
LGTM

**Comment by Madhura-08** [comment]
Can you please add testing details.
I have attached a text file for testing details.  
https://github.com/Seagate/cortx-ha/files/8469551/CORTX-30030_Test_Results.txt

**Review by shaileshsvc — APPROVED** [review]
Approved.

**Comment by akash2144** [comment]
{"source": "hare", "cluster_id": "803b244e189a4e7c92183027af8111c2", "site_id": "NOT_DEFINED", "rack_id": "NOT_DEFINED", "storageset_id": "1", "node_id": "", "resource_type": "cluster", "resource_id": "26c6dcbb2b6b4fcfafc2c9346585b756", "resource_status": "offline", "specific_info": ""}}
 
 I guess you have used wrong resource_id for testing. resource_id & cluster_id should be same in case of cluster events, right ?

**Comment by Madhura-08** [comment]
@akash2144 Yeah..Some local and setup testing details got mixed. Corrected now. Please check latest test file
https://jts.seagate.com/secure/attachment/513127/CORTX-30030_Test_Results.txt[Test_Results](url)

**Review by akash2144 — APPROVED** [review]

**Review by mariyappanp — APPROVED** [review]

**Review by gauri-bhosale — APPROVED** [review]

**Review by mukhtar-inamdar — APPROVED** [review]

**Comment by ArchanaLimaye** [comment]
are LLD updates done @Madhura-08 ?

**Comment by ArchanaLimaye** [comment]
@Madhura-08 can you please share the logs for health monitor also? Is alert being sent to health monitor ?

**Comment by ArchanaLimaye** [comment]
In test results ([https://jts.seagate.com/secure/attachment/513127/CORTX-30030_Test_Results.txt[Test_Results](url)] why is the parse event log seen as ERROR log ? can you please check ?

>> 2022-04-12 06:57:58 fault_tolerance [8]: ERROR [parse_event] Event 1649746677.5678144a25dbfe72537446fbdf848e7875e1928 is parsed and converted to object.

**Comment by Madhura-08** [comment]
In test results ([https://jts.seagate.com/secure/attachment/513127/CORTX-30030_[Test_Results](https://github.com/Seagate/cortx-ha/pull/url).txtTest_Results] why is the parse event log seen as ERROR log ? can you please check ?
@ArchanaLimaye that ERROR log I have added for my testing purpose in the parser..Just to check it has properly passed from parser or not. Its not a error at all.
I changed Log.debug to Log.error.

**Comment by Madhura-08** [comment]
can you please share the logs for health monitor also? Is alert being sent to health monitor ?
@ArchanaLimaye Newly performed the test which used mock monitor to send cluster offline event.
Consul key:
cortx>ha>v1>cortx>ha>system>cluster>803b244e189a4e7c92183027af8111c2>health:{"events": [{"event_timestamp": "1649823425.7102222", "created_timestamp": "1649823426", "status": "offline", "specific_info": ""}, {"event_timestamp": "1649823184", "created_timestamp": "1649823185", "status": "degraded", "specific_info": null}], "action": {"modified_timestamp": "1649823426", "status": "pending"}, "attributes": {}}

Health Monitor logs:
2022-04-13 04:17:06 health_monitor [7]: INFO [evaluate] Evaluated action [] for key action>cluster>offline

**Review by ArchanaLimaye — APPROVED** [review]

**Pull request merged**
